# krinry configuration v2.7.1
project:
  name: noraxlab
  type: flutter

build:
  default_type: debug
  output_path: build/app/outputs/flutter-apk

cloud:
  provider: github
  workflow: krinry-build.yml
  poll_interval: 8
